# Q4) Display all the orders along with product name ordered by a customer having Customer_Id=2

SELECT * FROM `ORDER`;
SELECT O.ORD_ID,O.ORD_DATE,O.ORD_AMOUNT,O.CUS_ID, SP.PRO_ID FROM `order` AS O
INNER JOIN supplier_pricing AS SP
ON O.PRICING_ID=SP.PRICING_ID;

SELECT * FROM PRODUCT AS P
INNER JOIN
(
	SELECT O.ORD_ID,O.ORD_DATE,O.ORD_AMOUNT,O.CUS_ID, SP.PRO_ID FROM `order` AS O
	INNER JOIN supplier_pricing AS SP
	ON O.PRICING_ID=SP.PRICING_ID
) AS T1 ON T1.PRO_ID = P.PRO_ID;


SELECT T1.ORD_ID,T1.ORD_DATE,T1.ORD_AMOUNT,T1.CUS_ID, P.PRO_ID FROM PRODUCT AS P
INNER JOIN
(
	SELECT O.ORD_ID,O.ORD_DATE,O.ORD_AMOUNT,O.CUS_ID, SP.PRO_ID FROM `order` AS O
	INNER JOIN supplier_pricing AS SP
	ON O.PRICING_ID=SP.PRICING_ID
) AS T1 ON T1.PRO_ID = P.PRO_ID;


SELECT C.CUS_ID,C.CUS_NAME, T2.ORD_ID,T2.ORD_DATE,T2.ORD_AMOUNT, T2.PRO_NAME FROM CUSTOMER AS C
INNER JOIN
(
	SELECT T1.ORD_ID,T1.ORD_DATE,T1.ORD_AMOUNT,T1.CUS_ID, P.PRO_ID , P.PRO_NAME FROM PRODUCT AS P
	INNER JOIN
	(
		SELECT O.ORD_ID,O.ORD_DATE,O.ORD_AMOUNT,O.CUS_ID, SP.PRO_ID FROM `order` AS O
		INNER JOIN supplier_pricing AS SP
		ON O.PRICING_ID=SP.PRICING_ID
	) AS T1 ON T1.PRO_ID = P.PRO_ID
) AS T2 ON T2.CUS_ID = C.CUS_ID;


SELECT C.CUS_ID,C.CUS_NAME, T2.ORD_ID,T2.ORD_DATE,T2.ORD_AMOUNT, T2.PRO_NAME FROM CUSTOMER AS C
INNER JOIN
(
	SELECT T1.ORD_ID,T1.ORD_DATE,T1.ORD_AMOUNT,T1.CUS_ID, P.PRO_ID , P.PRO_NAME FROM PRODUCT AS P
	INNER JOIN
	(
		SELECT O.ORD_ID,O.ORD_DATE,O.ORD_AMOUNT,O.CUS_ID, SP.PRO_ID FROM `order` AS O
		INNER JOIN supplier_pricing AS SP
		ON O.PRICING_ID=SP.PRICING_ID
	) AS T1 ON T1.PRO_ID = P.PRO_ID
) AS T2 ON T2.CUS_ID = C.CUS_ID AND C.CUS_ID=2;

