#Q9) Create a stored procedure to display supplier id, name, rating and Type_of_Service. For Type_of_Service, If rating =5, 
#print “Excellent Service”,If rating >4 print “Good Service”, If rating >2 print “Average Service” else print “Poor Service”.
 
SELECT *  FROM `ORDER` AS O
 INNER JOIN RATING AS R
 ON O.ORD_ID = R.ORD_ID;

 
 SELECT O.PRICING_ID,R.ORD_ID,R.RAT_RATSTARS  FROM `ORDER` AS O
 INNER JOIN 
 RATING AS R
 ON O.ORD_ID = R.ORD_ID;

 SELECT * FROM SUPPLIER_PRICING AS SP
 INNER JOIN (
 SELECT O.PRICING_ID,R.ORD_ID,R.RAT_RATSTARS  FROM `ORDER` AS O
 INNER JOIN 
 RATING AS R
 ON O.ORD_ID = R.ORD_ID) AS TEST 
 ON TEST.PRICING_ID = SP.PRICING_ID;


 SELECT SP.SUPP_ID,TEST.ORD_ID,TEST.RAT_RATSTARS FROM SUPPLIER_PRICING AS SP
 INNER JOIN  (
	SELECT O.PRICING_ID,R.ORD_ID,R.RAT_RATSTARS  FROM `ORDER` AS O 
	INNER JOIN 
	RATING AS R
 ON O.ORD_ID = R.ORD_ID)
 AS TEST ON TEST.PRICING_ID = SP.PRICING_ID;

 SELECT TEST2.SUPP_ID, SUM(TEST2.RAT_RATSTARS)/COUNT(TEST2.RAT_RATSTARS)  AS AVERAGE FROM
 (
	SELECT SP.SUPP_ID,TEST.ORD_ID,TEST.RAT_RATSTARS FROM SUPPLIER_PRICING AS SP
	INNER JOIN (
	SELECT O.PRICING_ID,R.ORD_ID,R.RAT_RATSTARS  FROM `ORDER` AS O
	INNER JOIN 
	RATING AS R
	ON O.ORD_ID = R.ORD_ID) AS TEST
    ON TEST.PRICING_ID = SP.PRICING_ID) AS TEST2 
    GROUP BY TEST2.SUPP_ID;
   
SELECT  FINAL.SUPP_ID, SUPPLIER.SUPP_NAME, FINAL.AVERAGE FROM
(SELECT TEST2.SUPP_ID, SUM(TEST2.RAT_RATSTARS)/COUNT(TEST2.RAT_RATSTARS)  AS AVERAGE FROM
	(SELECT SP.SUPP_ID,TEST.ORD_ID,TEST.RAT_RATSTARS FROM SUPPLIER_PRICING AS SP
	INNER JOIN (
	SELECT O.PRICING_ID,R.ORD_ID,R.RAT_RATSTARS  FROM `ORDER` AS O
	INNER JOIN 
	RATING AS R
	ON O.ORD_ID = R.ORD_ID) AS TEST 
	ON TEST.PRICING_ID = SP.PRICING_ID) AS TEST2 
	GROUP BY TEST2.SUPP_ID) AS FINAL 
	INNER JOIN SUPPLIER 
	ON  SUPPLIER.SUPP_ID = FINAL.SUPP_ID;

  
SELECT REPORT.SUPP_ID, REPORT.SUPP_NAME, REPORT.AVERAGE,
    CASE 
        WHEN REPORT.AVERAGE = 5 THEN 'Excellent Service'
        WHEN REPORT.AVERAGE > 4 THEN 'Good Service'
        WHEN REPORT.AVERAGE > 2 THEN 'Average Service'
        ELSE 'Poor Service'
    END AS Type_of_Service FROM 
    (
		SELECT FINAL.SUPP_ID, SUPPLIER.SUPP_NAME, FINAL.AVERAGE FROM 
        (
			SELECT TEST2.SUPP_ID,SUM(TEST2.RAT_RATSTARS) / COUNT(TEST2.RAT_RATSTARS) AS AVERAGE FROM 
            (
				SELECT SUPPLIER_PRICING.SUPP_ID, TEST.ORD_ID, TEST.RAT_RATSTARS FROM SUPPLIER_PRICING
				INNER JOIN 
                (
					SELECT `ORDER`.PRICING_ID, RATING.ORD_ID, RATING.RAT_RATSTARS FROM `ORDER`
					INNER JOIN RATING 
                    ON RATING.`ORD_ID` = `ORDER`.ORD_ID
				) AS TEST 
                ON TEST.PRICING_ID = SUPPLIER_PRICING.PRICING_ID
			) AS TEST2 GROUP BY SUPPLIER_PRICING.SUPP_ID
        ) AS FINAL 
        INNER JOIN SUPPLIER 
        ON FINAL.SUPP_ID = SUPPLIER.SUPP_ID 
	) AS REPORT;
