# Q6) Find the least expensive product from each category and print the table with category id, name, 

SELECT * FROM SUPPLIER_PRICING;
SELECT PRO_ID, min(SUPP_PRICE) AS MIN_PRICE from SUPPLIER_PRICING GROUP BY PRO_ID;

SELECT * FROM PRODUCT
INNER JOIN 
	(
		select PRO_ID, min(SUPP_PRICE) AS MIN_PRICE from SUPPLIER_PRICING GROUP BY PRO_ID
	) AS T1 ON PRODUCT.PRO_ID = T1.PRO_ID;

SELECT * FROM CATEGORY
INNER JOIN
(
	SELECT * FROM PRODUCT
	INNER JOIN 
	(
		select PRO_ID, min(SUPP_PRICE) AS Min_Price from SUPPLIER_PRICING GROUP BY PRO_ID
	) AS T1 ON PRODUCT.PRO_ID = T1.PRO_ID
) AS T2 ON T2.CAT_ID= CATEGORY.CAT_ID;

SELECT * FROM CATEGORY
INNER JOIN
(
	SELECT PRODUCT.PRO_ID, PRODUCT.PRO_NAME,PRODUCT.CAT_ID,T1.MIN_PRICE FROM PRODUCT
	INNER JOIN 
	(
		SELECT PRO_ID, min(SUPP_PRICE) AS MIN_PRICE from SUPPLIER_PRICING GROUP BY PRO_ID
	) AS T1 ON PRODUCT.PRO_ID = T1.PRO_ID
) AS T2 ON T2.CAT_ID= CATEGORY.CAT_ID;

SELECT CATEGORY.CAT_ID, CATEGORY.CAT_NAME, MIN(t3.min_price) AS MIN_PRICE FROM CATEGORY 
INNER JOIN 
(
	SELECT PRODUCT.CAT_ID, PRODUCT.PRO_NAME, T2.* FROM PRODUCT
    INNER JOIN 
    (
		SELECT PRO_ID, MIN(supp_price) AS MIN_PRICE FROM SUPPLIER_PRICING  GROUP BY PRO_ID
	) AS T2 WHERE T2.PRO_ID = PRODUCT.PRO_ID
) AS T3 WHERE T3.CAT_ID = CATEGORY.CAT_ID
GROUP BY T3.CAT_ID;

SELECT CATEGORY.CAT_ID, CATEGORY.CAT_NAME, MIN(T3.min_price) AS MIN_PRICE FROM CATEGORY 
INNER JOIN 
(
	SELECT PRODUCT.CAT_ID, PRODUCT.PRO_NAME, T2.* FROM PRODUCT
    INNER JOIN 
    (
		SELECT pro_id, MIN(supp_price) AS Min_Price FROM SUPPLIER_PRICING  GROUP BY PRO_ID
	) AS T2 WHERE T2.pro_id = PRODUCT.PRO_ID
) AS T3 WHERE T3.CAT_ID = CATEGORY.CAT_ID
GROUP BY T3.CAT_ID;