# Q3) Display the total number of customers based on gender who have placed orders of worth at least Rs.3000.

SELECT * FROM `order`;
SELECT * FROM `ORDER` AS O
INNER JOIN CUSTOMER AS C
ON C.CUS_ID =O.CUS_ID;

SELECT * FROM `ORDER` AS O
INNER JOIN CUSTOMER AS C
ON C.CUS_ID =O.CUS_ID HAVING O.ORD_AMOUNT>=3000;

SELECT C.CUS_ID, CUS_NAME,CUS_GENDER,O.ORD_ID,O.ORD_AMOUNT FROM `ORDER` AS O
INNER JOIN CUSTOMER AS C
ON O.CUS_ID =C.CUS_ID
HAVING O.ORD_AMOUNT>=3000;





